{{- $awsAccessKey := ((lookup "v1" "Secret" "control-plane" "s3-user-credentials").data.username | b64dec) }}
{{- $awsSecretKey := ((lookup "v1" "Secret" "control-plane" "s3-user-credentials").data.password | b64dec) }}
apiVersion: v1
kind: Secret
metadata:
  name: central-components-aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ $awsAccessKey | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ $awsSecretKey | b64enc | quote }}
