{{- $awsAccessKey := ((lookup "v1" "Secret" "control-plane" "s3-user-credentials").data.username | b64dec) }}
{{- $awsSecretKey := ((lookup "v1" "Secret" "control-plane" "s3-user-credentials").data.password | b64dec) }}
apiVersion: v1
kind: Secret
metadata:
  name: central-components-backups
type: Opaque
data:
  cloud: {{ printf "[default]\naws_access_key_id=%s\naws_secret_access_key=%s\n" $awsAccessKey $awsSecretKey | b64enc | quote }}
